<?php $helper = $this->helper('CleverSoft\CleverSocialLogin\Helper\Data'); ?>
<?php if ($helper->photoEnabled()): ?>
    <li class="pslogin-welcome-msg" data-bind="scope: 'pslogin-photo'" data-mage-init='{"Magento_Ui/js/core/app":<?php echo $block->getJsLayout();?>}'>
    	<!-- ko if: pslogin().photo -->
        <img data-bind="attr: {'src' : pslogin().photo, 'alt': customer().fullname }" src="" alt="" />
       	<!-- /ko -->
    </li>
<?php endif; ?>