<?php
/**
 * @author CleverSoft Team
 * @copyright Copyright (c) 2016 CleverSoft
 * @package CleverSoft_LayeredNavigation
 */
?>
<!-- cleversoft_shopby_not_remove_tags -->
<div class="rating-summary" style="display: inline-block;margin-top: -5px;">
    <div class="rating-result" title="<?php echo ($block->getStar()*20);?>%">
        <span style="width:<?php echo ($block->getStar()*20);?>%"><span><?php echo $block->getStar();?></span></span>
    </div>
</div>