<?php
/**
 * @author CleverSoft Team
 * @copyright Copyright (c) 2016 CleverSoft
 * @package CleverSoft_CleverLayeredNavigation
 */
?>
<?php
/**
 * @var $block \CleverSoft\CleverLayeredNavigation\Block\Navigation\FilterCollapsing
 */

if(!$block->canShowBlock()) {
    return;
}
?>

<script type="text/x-magento-init">
            {
                "#narrow-by-list": {
                    "accordion": {
                        "multipleCollapsible": true,
                        "active": [<?php echo implode(",", $block->getFiltersExpanded())?>]
                    }
                }
            }
</script>
