<?php
/**
 * @category    MT
 * @package    Clever Product Composer
 * Copyright (C) 2008-2016 ZooExtension.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
?>
<?php
/* @var $this CleverProduct_Block_Widget */
use CleverSoft\CleverProduct\Block\Widget\Collection;
$_id = $block->getConfig('id');
$_title = $block->getConfig('widget_title');
$t = microtime();
///t var
$type = $block->getData('layout');

$tab = $block->getData('widget_tab');
$tabs = $block->getTabs();

switch ($type) {
    case 'list':
        if ($tab == 'categories' || $tab == 'collections') {require __DIR__.'/cases/tab.phtml';
        }else { echo $block->renderCollection('collections', $block->getConfig('mode'), 'widget/cases/list.phtml');}
        break;

    case 'grid':
        if ($tab == 'categories' || $tab == 'collections') {
            require __DIR__.'/cases/tab.phtml';
        }else {
            echo $block->renderCollection('collections', $block->getConfig('mode'), 'widget/cases/grid.phtml');
        }
        break;

    case 'grid2':
        if ($tab == 'categories' || $tab == 'collections') {
            require __DIR__.'/cases/tab.phtml';
        }else {
            echo $block->renderCollection('collections', $block->getConfig('mode'), 'widget/cases/grid2.phtml');
        }
        break;

	case 'carousel-vertical':
        if ($tab == 'categories' || $tab == 'collections') {
            require __DIR__.'/cases/tab.phtml';
        }else {
            echo $block->renderCollection('collections', $block->getConfig('mode'), 'widget/cases/carousel_vertical.phtml');
        }
        break;
    default:
        if ($tab == 'categories' || $tab == 'collections') {
            require __DIR__.'/cases/tab.phtml';
        } else {
            if ($type == 'carousel') {
                echo $block->renderCollection('collections', $block->getConfig('mode'), 'widget/cases/carousel.phtml');
            } else {
                ?>
                <div class="<?php echo $block->getConfig('classes') ?> zoo-product-collection02" id="<?php echo $_id ?>">
                    <?php if ($_title): ?>
                        <div class="zoo-main-heading">
                            <div class="zoo-heading-wrapper-title">
                                <h3><span><?php echo $_title ?></span></h3>
                            </div>
                        </div>
                    <?php endif ?>

                    <?php echo $block->renderCollection('collections', $block->getConfig('mode'), 'widget/cases/list.phtml') ?>
                </div>
            <?php
            }
        }
        break;
}


