<?php
/**
 * @author CleverSoft Team
 * @copyright Copyright (c) 2016 CleverSoft
 * @package CleverSoft_CleverLayeredNavigation
 */
?>
<?php
/** @var $block \CleverSoft\CleverLayeredNavigation\Block\Adminhtml\Page\Selection */
?>
<script>
    require([
        'CleverSoft_CleverLayeredNavigation/js/selection'
    ], function (selection) {
        selection.init('<?php
            echo $block->getSelectionUrl()
        ?>', '<?php
            echo $block->getAddSelectionUrl()
        ?>', '<?php
            echo $block->getCounter()
        ?>')
        window.cleversoftLayeredNavigationSelection = selection;
    })
</script>