<?php
/**
 * @author CleverSoft Team
 * @copyright Copyright (c) 2016 CleverSoft
 * @package CleverSoft_CleverLayeredNavigation
 */
?>
<?php
/**
 * @var $block \CleverSoft\CleverLayeredNavigation\Block\Product\ProductList\Ajax
 */
if(!$block->canShowBlock()) {
    return;
}
?>
<script type="text/x-magento-init">
{
    "body.page-with-filter": {
        "cleverLayeredNavigationAjax": {}
        }
}
</script>
